services:

  bank:
    image: "epitechregistry.azurecr.io/bank:latest"
    build: ./bank
    container_name: bank
    ports:
      - 4000:4000
    env_file:
      - .env.bank.development
    environment:
      - DATABASE_HOST=mongo
    depends_on:
      - mongo

  server:
    image: "epitechregistry.azurecr.io/cash-manager:latest"
    build: ./server
    container_name: server
    ports:
      - 3000:3000
    env_file:
      - .server.env.development
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
    volumes:
      - ./server/public/:/app/public/
      - ./server/src/:/app/src/
    command: npm run dev

  # dashboard:
  #   build: ./dashboard
  #   container_name: dashboard
  #   ports:
  #     - 80:3000
  #   env_file:
  #     - .server.env.development
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - ./dashboard/public/:/app/public/
  #     - ./dashboard/src/:/app/src/
  #   command: npm run start

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    env_file:
      - .server.env.development
    volumes:
      - ./mongo_data/:/data/db
      - ./mongo_data/:/data/configdb
