FROM node:alpine

ENV NODE_ENV=production
ENV REACT_APP_API_URL=http://localhost:3000/api
ENV PORT=3000

WORKDIR /app

COPY package*.json .
RUN npm ci

COPY . .

RUN npm run build

CMD [ "npm", "run", "start" ]