# bank ENV
apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-configmap
data:
  container_port: "4000"
  jwt_exp: "86400"
  jwt_issuer: "cash-manager"
  cors_allowed_origin: "*"
  path_prefix: "/bank"
---
# bank ENV SECRETS (BASE64)
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bank-secrets
data:
  # 8cfcd9b78345
  jwt_secret: "OGNmY2Q5Yjc4MzQ1"
  # mongodb+srv://cashmanager:ZmM5OTlkOWQ%3D@database-cluster-svc.default.svc.cluster.local/bank?authSource=admin&replicaSet=database-cluster&ssl=false
  # database_uri: "bW9uZ29kYitzcnY6Ly9jYXNobWFuYWdlcjpabU01T1Rsa09XUSUzREBkYXRhYmFzZS1jbHVzdGVyLXN2Yy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsL2Jhbms/YXV0aFNvdXJjZT1hZG1pbiZyZXBsaWNhU2V0PWRhdGFiYXNlLWNsdXN0ZXImc3NsPWZhbHNl"
  # mongodb+srv://cashmanager:P8Awrc7ZdINAGft9@epitech-cluster.a5zbguu.mongodb.net/bank?retryWrites=true&w=majority
  database_uri: bW9uZ29kYitzcnY6Ly9jYXNobWFuYWdlcjpQOEF3cmM3WmRJTkFHZnQ5QGVwaXRlY2gtY2x1c3Rlci5hNXpiZ3V1Lm1vbmdvZGIubmV0L2Jhbms/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
---
# bank DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank
  labels:
    tier: bank
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      tier: bank
  template:
    metadata:
      labels:
        tier: bank
    spec:
      containers:
        - name: bank
          image: docker.io/antoineleguillou/cash-manager_bank:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 350m
              memory: 450Mi
            requests:
              cpu: 300m
              memory: 320Mi
          env:
            - name: CONTAINER_PORT
              valueFrom:
                configMapKeyRef:
                  name: bank-configmap
                  key: container_port
            - name: JWT_EXP
              valueFrom:
                configMapKeyRef:
                  name: bank-configmap
                  key: jwt_exp
            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: bank-configmap
                  key: jwt_issuer
            - name: CORS_ALLOWED_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: bank-configmap
                  key: cors_allowed_origin
            - name: PATH_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: path_prefix
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: jwt_secret
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: bank-secrets
                  key: database_uri
          ports:
            - containerPort: 4000
      restartPolicy: Always
---
# bank SERVICES
# apiVersion: v1
# kind: Service
# metadata:
#   name: bank
# spec:
#   selector:
#     tier: bank
#   type: ClusterIP
#   ports:
#     - port: 4000
#       targetPort: 4000
#       name: http
---
apiVersion: v1
kind: Service
metadata:
  name: bank
  namespace: default
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    tier: bank
  type: NodePort
---

