# server ENV
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-configmap
data:
  port: "3000"
  session_expire: "2d"
  path_prefix: "/cashmanager"
---
# server ENV SECRETS (BASE64)
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: server-secrets
data:
  # 8cfcd9b78345
  session_secret: "OGNmY2Q5Yjc4MzQ1"
  # mongodb+srv://cashmanager:ZmM5OTlkOWQ%3D@database-cluster-svc.default.svc.cluster.local/cashmanager?authSource=admin&replicaSet=database-cluster&ssl=false
  # database_uri: "bW9uZ29kYitzcnY6Ly9jYXNobWFuYWdlcjpabU01T1Rsa09XUSUzREBkYXRhYmFzZS1jbHVzdGVyLXN2Yy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsL2Nhc2htYW5hZ2VyP2F1dGhTb3VyY2U9YWRtaW4mcmVwbGljYVNldD1kYXRhYmFzZS1jbHVzdGVyJnNzbD1mYWxzZQ=="
  # mongodb+srv://cashmanager:P8Awrc7ZdINAGft9@epitech-cluster.a5zbguu.mongodb.net/cashmanager?retryWrites=true&w=majority
  database_uri: bW9uZ29kYitzcnY6Ly9jYXNobWFuYWdlcjpQOEF3cmM3WmRJTkFHZnQ5QGVwaXRlY2gtY2x1c3Rlci5hNXpiZ3V1Lm1vbmdvZGIubmV0L2Nhc2htYW5hZ2VyP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
---
# server DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    tier: server
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      tier: server
  template:
    metadata:
      labels:
        tier: server
    spec:
      containers:
        - name: server
          image: docker.io/antoineleguillou/cash-manager_server:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 350m
              memory: 450Mi
            requests:
              cpu: 300m
              memory: 320Mi
          env:
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: session_secret
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: port
            - name: SESSION_EXPIRE
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: session_expire
            - name: PATH_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: path_prefix
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: database_uri
          ports:
            - containerPort: 3000
      restartPolicy: Always
---
# server SERVICES
# apiVersion: v1
# kind: Service
# metadata:
#   name: server
# spec:
#   selector:
#     tier: server
#   type: ClusterIP
#   ports:
#     - port: 3000
#       targetPort: 3000
#       name: http
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: default
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    tier: server
  type: NodePort
---

