FROM node:alpine

RUN apk add --no-cache tini

ENV PORT=3000

ENV MONGO_HOST=mongo
ENV MONGO_USERNAME=cashmanager_user
ENV MONGO_PASSWORD=ZTZkYWZmZWMtZTA3Mi00ZDNhLTk5MDktMWViMTk4MDNmNTQxCg=
ENV MONGO_DATABASE=cashmanager_db

ENV SESSION_EXPIRE=2d
ENV SESSION_SECRET=YjkzZDUwNGMtMzViNC00N2EyLWExOGYtMGVlYzU1OTFiZDY3Cg==

WORKDIR /app

COPY ./package*.json .

RUN npm ci

COPY . .

RUN npm run build

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["node", "./build/main.js"]