FROM --platform=linux/amd64 node:alpine

RUN apk add --no-cache tini

ENV NODE_ENV=production

WORKDIR /app

COPY ./package*.json .

RUN npm install --loglevel verbose

COPY . .

RUN npm run build

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["node", "./build/main.js"]