export enum AuthActionTypes {
    AUTH_LOGOUT = "AUTH_LOGOUT",
    FETCH_LOGIN_DETAILS = "FETCH_LOGIN_DETAILS",
    FETCH_LOGIN_DETAILS_SUCCESS = "FETCH_LOGIN_DETAILS_SUCCESS",
    FETCH_LOGIN_DETAILS_ERROR = "FETCH_LOGIN_DETAILS_ERROR",

    FETCH_USER_DETAILS = "FETCH_USER_DETAILS",
    FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS",
    FETCH_USER_DETAILS_ERROR = "FETCH_USER_DETAILS_ERROR",
}

export enum AuthRegActionTypes {
    POST_USER_DETAILS = "POST_USER_DETAILS",
    POST_USER_DETAILS_SUCCESS = "POST_USER_DETAILS_SUCCESS",
    POST_USER_DETAILS_ERROR = "POST_USER_DETAILS_ERROR",
}
  